### ISSUE TITLE
[Feature] atlas with lower resolution 

### ISSUE THREAD

**Issue by zhiwen10** [SainsburyWellcomeCentre/cellfinder#107]
Hi Adam, 
Is there atlas available to share with 25um or 50um resolution? I can see the [link](http://help.brain-map.org/display/mouseconnectivity/API#API-DownloadAtlas) you provided from Allen website in your documentation only has template and annotation atlas files. For amap to work, we also need template_filtered.nii and hemisphere.nii files for 25um and 50um resolution. Are they trivial to generate? I could not think of a good way to generate this hemisphere.nii yet, especially. Could you share your thoughts on this?

The reasons why I ask is that, amap registration is RAM demanding. I only just managed to register  10um voxel resolution data in my 32GB RAM. It did not take 5um voxel resolution data (14GB). Anyways, for my purpose, I only need to register electrode tract, so 25um or 50um resolution would be enough. And with lower resolution atlas, I'm hoping cellfinder can work on a normal laptop.

**Comment by zhiwen10** [comment]
Guess it can be trivial to just pass a logical find filter to annotation matrix, and assign 1 or 2 to left or right hemisphere? Is that how you would do this? How about template_filter.nii? Can amap take template_25um.nii as raw data, and output template_filter_25um.nii without the correct atlas files?

**Comment by adamltyson** [comment]
Hi Zhiwen,

I'll share more thoughts next week, but basically this is something that will definitely be done, it just takes a bit of work to make it work properly.

The voxel size of your input data shouldn't affect the RAM usage though, only the physical size of the image (they get downsampled). You could try cropping the image to the brain if you're running out of RAM.

**Comment by adamltyson** [comment]
see also https://github.com/SainsburyWellcomeCentre/amap-python/issues/2

**Comment by zhiwen10** [comment]
Thanks. Just checked on hemisphere.nii file in 10um atlas folder, looks like it is just two values for left and right hemisphere split from midline. Guess Just need template_filter.nii. I will test it it out if I get sometime before you, and will let you know. 
Yes, that's what i meant. I need to downsample my raw data to lower resolution (2GB at 10um rez, not 14GB at 5um rez) a lot to fit into RAM (32GB).

**Comment by adamltyson** [comment]
Generating the files is straightforward, the complication is making it work properly with the rest of the software. 

Amap/cellfinder will downsample data for you, I usually register 1um voxels on my laptop, so it might be that the physical image is too big (in mm).

**Comment by zhiwen10** [comment]
Okay, make sense. Guess the package was never tested for other atlas not 10um, some parameters could be hard coded. 
Yes, I understand amap/cellfinder can downsample data to 10um. Just surprised that 14GB raw data is too large to work in amap for 32GB RAM.
Keep me updated. Thanks!

**Comment by adamltyson** [comment]
As I say, 14GB shouldn’t be too big, I’ve registered 500GB raw data on 32GB.

**Comment by zhiwen10** [comment]
Now I see what you mean. Thought you had a super powerful laptop with hundreds of RAM😂 
I went back to ran my raw data (14GB, lightsheet data in horizontal orientation (flipped compared to atlas brain.nii, 5.9x5.9x5 um). It get stuck at loading images. Tries all'--flip-x', '--flip-y', 'flip-z'.
Code:
`(cellfinder) E:\>cellfinder -s "E:\idisco\PV_0007\190917_488_hor_11-37-36" -b "E:\idisco\PV_0007\190917_488_hor_11-37-36" -o "E:\idisco\PV_0007\190917_488_hor_11-37-36_output2" -x 5.9 -y 5.9 -z 5 --orientation horizontal --register --no-detection --no-classification`

Error:
`2020-05-08 02:47:40 AM - INFO - MainProcess fancylog.py:265 - Starting logging
2020-05-08 02:47:40 AM - INFO - MainProcess fancylog.py:267 - Multiprocessing-logging module found. Logging from all processes
2020-05-08 02:47:40 AM - INFO - MainProcess main.py:32 - Registering to atlas
2020-05-08 02:47:40 AM - INFO - MainProcess prep.py:401 - Checking whether the atlas exists
2020-05-08 02:47:40 AM - INFO - MainProcess main.py:98 - Preprocessing data for registration
2020-05-08 02:47:40 AM - INFO - MainProcess main.py:99 - Loading data
pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
2020-05-08 02:47:40 AM - INFO - MainProcess batteryrunners.py:274 - pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
2020-05-08 02:47:40 AM - INFO - MainProcess brain_processor.py:79 - Loading raw image data
Loading images:   0%|                                                                                                                                                                               | 0/133 [00:11<?, ?plane/s]

Loading images:   0%|                                                                                                                                                                               | 0/133 [00:11<?, ?plane/s]



Loading images:   0%|                                                                                                                                              Loading images:   0%|                                                                                                                                              Loading images:   0%|                                                                                                                                              Loading images:   0%|                                                                                                                                                                               | 0/133 [02:34<?, ?plane/s]



concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "e:\miniconda3\envs\cellfinder\lib\concurrent\futures\process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "e:\miniconda3\envs\cellfinder\lib\site-packages\brainio\brainio.py", line 313, in load_from_paths_sequence
    len(paths_sequence),
  File "e:\miniconda3\envs\cellfinder\lib\site-packages\brainio\utils.py", line 34, in check_mem
    "Needed {}, only {} available.".format(total_size, free_mem)
brainio.utils.BrainIoLoadException: Not enough memory on the system to complete loading operationNeeded 676366663311.36, only 20238336 available.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\miniconda3\envs\cellfinder\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\miniconda3\envs\cellfinder\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\miniconda3\envs\cellfinder\Scripts\cellfinder.exe\__main__.py", line 7, in <module>
  File "e:\miniconda3\envs\cellfinder\lib\site-packages\cellfinder\main.py", line 61, in main
    debug=args.debug,
  File "e:\miniconda3\envs\cellfinder\lib\site-packages\amap\main.py", line 111, in main
    n_free_cpus=n_free_cpus,
  File "e:\miniconda3\envs\cellfinder\lib\site-packages\amap\register\brain_processor.py", line 87, in __init__
    n_free_cpus=n_free_cpus,
  File "e:\miniconda3\envs\cellfinder\lib\site-packages\brainio\brainio.py", line 79, in load_any
    n_free_cpus=n_free_cpus,
  File "e:\miniconda3\envs\cellfinder\lib\site-packages\brainio\brainio.py", line 194, in load_from_folder
    paths, x_scaling_factor, y_scaling_factor, n_free_cpus=n_free_cpus
  File "e:\miniconda3\envs\cellfinder\lib\site-packages\brainio\brainio.py", line 285, in threaded_load_from_sequence
    stack = np.dstack([s.result() for s in stacks])
  File "e:\miniconda3\envs\cellfinder\lib\site-packages\brainio\brainio.py", line 285, in <listcomp>
    stack = np.dstack([s.result() for s in stacks])
  File "e:\miniconda3\envs\cellfinder\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "e:\miniconda3\envs\cellfinder\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
brainio.utils.BrainIoLoadException: Not enough memory on the system to complete loading operationNeeded 676366663311.36, only 20238336 available.`

**Comment by zhiwen10** [comment]
I pressed control-c after a while with no update, or at progress bar showed up with nothing in progress.

**Comment by adamltyson** [comment]
Any chance you could send me the raw data?

Also I think using amap directly will use a bit less RAM (and work a bit quicker). 

https://sainsburywellcomecentre.github.io/amap-python/main/user_guide/run.html

**Comment by zhiwen10** [comment]
When I prepare to concatenate the tiff files to a single one to send to you, I realised it is the unconventional naming scheme of the raw data causing the problem. They were named as such: '11-37-36_488_hor_UltraII_C00_xyz-Table Z0000.ome.tif'. I have changed them to '190917_488_0000.tif', and it's loading fine.

**Comment by adamltyson** [comment]
Closing this. See https://github.com/SainsburyWellcomeCentre/amap-python/issues/2 for progress of adding additional atlases
