### ISSUE TITLE
[Feature] visualization of multiple probes in common 3D atlas

### ISSUE THREAD

**Issue by zhiwen10** [SainsburyWellcomeCentre/cellfinder#109]
Adam is planning to register probe in Atlas with a GUI. Would be nice to extrapolate all probe site from the florescent track, and assign each sites to a brain area automatically, which is relatively easy to do. 3D visualization of  all probe location in a common atlas in brainrender is also informative.

[[BUG]error message with reverse transformation in 'cellfinder_cell_standard' #108 ](https://github.com/SainsburyWellcomeCentre/cellfinder/issues/108)

**Comment by zhiwen10** [comment]
Straight probe became bended in #108 example above, after reverse transformation. Transformation of data points look correct in first glance. Maybe such bend can not be avoided, as transformation for each area is not linear. If the probe is required to be straight after transformation for visualization, we can just transform only two points on the probe instead.

**Comment by adamltyson** [comment]
Unfortunately, if your sample is warped non-linearly (relative to the atlas), then the track will always be bent. We could force it to be linear, but then it would pass through "incorrect" regions.

**Comment by adamltyson** [comment]
Linked to https://github.com/SainsburyWellcomeCentre/neuro/issues/13

**Comment by adamltyson** [comment]
Hi @zhiwen10, there's a prototype of this tool of you wanted to try it out. It's likely to change, and there are many bugs remaining. 

It's added to `neuro`. Install with `pip install --upgrade --pre`. Basic docs [here](https://docs.cellfinder.info/neuro/standalone-tools/manual-segmentation)

Overview:
* Run amap, passing the channel with the track to segment to the `--downsample` flag
* Run `manual_seg` passing the downsampled image to be segmented, and the amap output directory
* Trace the track in the GUI:
![GUI](https://user-images.githubusercontent.com/13147259/83886889-9868ba80-a73f-11ea-8ec0-9e0d2c8a525f.png)
* It will then perform spline interpolation, and you can save where each region of the track is:

| Track position                 | Region ID | Acronym  | Name   |
|-------------------------|--------|---------|--------------------------------|
| 41                      | 593    | VISp1   | Primary visual area, layer 1   | 1" 
| 42                      | 593    | VISp1   | Primary visual area, layer 1   | 1"   |
| 43                      | 593    | VISp1   | Primary visual area, layer 1   | 1"   |
| 44                      | 593    | VISp1   | Primary visual area, layer 1   | 1"   |
| 45                      | 593    | VISp1   | Primary visual area, layer 1   | 1"   |
| 46                      | 593    | VISp1   | Primary visual area, layer 1   | 1"   |
| 47                      | 821    | VISp2/3 | Primary visual area, layer 2/3 | 1"   |
| 48                      | 821    | VISp2/3 | Primary visual area, layer 2/3 | 1"   |
| 49                      | 821    | VISp2/3 | Primary visual area, layer 2/3 | 1"   |
| 50                      | 821    | VISp2/3 | Primary visual area, layer 2/3 | 1"   |
| 51                      | 821    | VISp2/3 | Primary visual area, layer 2/3 | 1"   |

* You can then visualise in 3D in brainrender:
![3D](https://user-images.githubusercontent.com/13147259/83887324-32c8fe00-a740-11ea-9682-2b06b60113f5.png)

**Comment by zhiwen10** [comment]
Thanks, Adam. Looks impressive. Definitely not easy to implement all into one GUI as I thought. I will definitely try it out for next samples. At the moment, I use background subtraction and thresholding to get track position, then transform to standard atlas, followed by [BrainRender with SHARP-Track method](https://github.com/BrancoLab/BrainRender/issues/44). Manual labeling of the track is more efficient and easier to work around for multiple shanks in one sample, as the method you provided. Thank you for streamline the process. Very useful.

**Comment by adamltyson** [comment]
Released in version 0.3.14 see [docs](https://docs.cellfinder.info/neuro/standalone-tools/manual-segmentation).
