### ISSUE TITLE
[BUG] amap registration: reg_aladin.exe has stopped working

### ISSUE THREAD

**Issue by rdbcasillas** [SainsburyWellcomeCentre/cellfinder#116]
**Describe the bug**
While performing  amap registration, after  starting "affine registration", the amap program throws a dialog box saying "reg_aladin.exe has stopped working"

**To Reproduce**
The command that gave this error: 

```
amap "C:\Users\7057mehrav\Downloads\145-063-better-cropped" "C:\Users\7057mehrav\Downloads\145-063-output" -x 10 -y 10 -z 20

```

**Expected behavior**
Output folder with bunch of ".nii" files after  successful registration

**Log file**
The error log didn't save any output so I am pasting the log from the console right here: 

```
2020-06-13 13:01:34 PM - INFO - MainProcess main.py:203 - Starting affine registration
Traceback (most recent call last):
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\imlib\general\system.py", line 275, in safe_execute_command
    cmd, stdout=log_file, stderr=error_file, shell=True
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\imlib\bin\nifty_reg\win64\reg_aladin -ln 6 -lp 5 -flo C:\Users\7057mehrav\Downloads\145-063-output\brain_filtered.nii -ref C:\Users\7057mehrav\Downloads\145-063-output\downsampled_filtered.nii -aff C:\Users\7057mehrav\Downloads\145-063-output\affine_matrix.txt -res C:\Users\7057mehrav\Downloads\145-063-output\affine_registered_atlas_brain.nii -omp 44' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\amap\register\brain_registration.py", line 76, in register_affine
    self.paths.tmp__affine_error_path,
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\imlib\general\system.py", line 300, in safe_execute_command
    cmd,
imlib.general.system.SafeExecuteCommandError:
-------------------------
Process failed:
 -------------------------

-------------------------
please read the logs at C:\Users\7057mehrav\Downloads\145-063-output\affine.log and C:\Users\7057mehrav\Downloads\145-063-output\affine.err
-------------------------
command: c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\imlib\bin\nifty_reg\win64\reg_aladin -ln 6 -lp 5 -flo C:\Users\7057mehrav\Downloads\145-063-output\brain_filtered.nii -ref C:\Users\7057mehrav\Downloads\145-063-output\downsampled_filtered.nii -aff C:\Users\7057mehrav\Downloads\145-063-output\affine_matrix.txt -res C:\Users\7057mehrav\Downloads\145-063-output\affine_registered_atlas_brain.nii -omp 44
-------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\7057mehrav\AppData\Local\Continuum\anaconda3\envs\cellfinder2\Scripts\amap.exe\__main__.py", line 7, in <module>
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\amap\cli.py", line 480, in main
    run()
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\amap\cli.py", line 458, in run
    debug=args.debug,
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\amap\main.py", line 204, in main
    brain_reg.register_affine()
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\amap\register\brain_registration.py", line 80, in register_affine
    "Affine registration failed; {}".format(err)
imlib.general.exceptions.RegistrationError: Affine registration failed;
-------------------------
Process failed:
 -------------------------

-------------------------
please read the logs at C:\Users\7057mehrav\Downloads\145-063-output\affine.log and C:\Users\7057mehrav\Downloads\145-063-output\affine.err
-------------------------
command: c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\cellfinder2\lib\site-packages\imlib\bin\nifty_reg\win64\reg_aladin -ln 6 -lp 5 -flo C:\Users\7057mehrav\Downloads\145-063-output\brain_filtered.nii -ref C:\Users\7057mehrav\Downloads\145-063-output\downsampled_filtered.nii -aff C:\Users\7057mehrav\Downloads\145-063-output\affine_matrix.txt -res C:\Users\7057mehrav\Downloads\145-063-output\affine_registered_atlas_brain.nii -omp 44
-------------------------

```

**Screenshots**
![image](https://user-images.githubusercontent.com/9725334/84575949-b1700c00-adce-11ea-84ad-d656f2fe9cfd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I was given an Imaris file (.ims) that had the "z" dimension > 2048 (amap complained when I ran registration with the original file). So I cropped the z dimension and after cropping, the dimension of the imaris files were these:   

![image](https://user-images.githubusercontent.com/9725334/84576031-3fe48d80-adcf-11ea-8761-f1ec91942da9.png)

This imaris file was then saved as a "series of TIFs" into a folder, which then became the input for amap. 

Please let me know if I need to provide more details. 

Thanks,
Vatsal

**Comment by adamltyson** [comment]
If they exist, could you attach `affine.err` and `affine.log`?

**Comment by rdbcasillas** [comment]
They were created but they have absolutely zero data in them.

**Comment by rdbcasillas** [comment]
Hi @adamltyson,

Is there anything else that I can provide to help with understanding this issue?

**Comment by adamltyson** [comment]
Hmm, I don't know. I presume you've tried again to see if it works?

Could you try:
* Run with another image (or just a different export of the same image)
* Run from scratch (i.e into a different output folder)
* Run with `--n-free-cpus`  set to something like 30 (it looks like your machine has a lot of CPU cores, the openMP parallelization might be doing something weird). 
* Reinstall into a new conda environment

**Comment by adamltyson** [comment]
Weird. If you have time, would you mind installing it all again? I'd be interested to know whether the issue is the new versions of cellfinder & amap (that shouldn't have changed anything to do with the registration), or whether your second download of cellfinder was incomplete/corrupted somehow.

**Comment by rdbcasillas** [comment]
So I did create a new conda environment and reinstalled everything. And it worked! 

I should mention some errors that i noticed when I did ```pip install amap```  *after* installing cellfinder using ``` conda create --name cellfinder-test python=3.7```: 

```
ERROR: allensdk 2.0.1 has requirement scikit-image<0.17.0,>=0.14.0, but you’ll have scikit-image 0.17.2 which is incompatible.
ERROR: neuro 0.0.16 has requirement scikit-image==0.16.2, but you’ll have scikit-image 0.17.2 which is incompatible.
ERROR: amap 0.1.26 has requirement scikit-image==0.16.2, but you’ll have scikit-image 0.17.2 which is incompatible.
```
These errors didn't seem to cause any issue. 

I will close this issue now but I have one more tangential question: 

Is there any documentation on the output files that amap registration results in? I want to visualize this registration data (along with marked cells) using Brainrender. While using Brainrender, no matter what ".nii" file I use (from amap output), I only get a blank brain 3d image. 

Thanks again for all the help and suggestions!

**Comment by adamltyson** [comment]
> Is there any documentation on the output files that amap registration results in? I want to visualize this registration data (along with marked cells) using Brainrender.

So brainrender is typically used for visualisation of data in standard space, and not for single subject data. Theoretically you could do it, but it would be very hard to visualise the registration in 3D. The easiest way to visualise the registration results currently is to use `cellfinder_view`.

If you want to visualise cells detected in cellfinder, there is a tool supplied to convert your `cells_in_standard_space.xml` into a format that brainrender can load (see [here](https://docs.cellfinder.info/neuro/standalone-tools/exporting-detected-cell-positions-to-brainrender)). In the future, cellfinder and brainrender will be better integrated.

If you are interested in loading the `.nii` files from amap into python, you can use [brainio](https://github.com/adamltyson/brainio) to load them as numpy arrays:
```python
from brainio import brainio
image = brainio.load_any("image_file.nii")
```

You can also load nii images directly into brainrender by using `brainrender.scene.add_image()` (which uses brainio). However, it will convert the image into a mesh, so you would just get a single "shape" to visualise.

If you think there is anything that should be added to cellfinder/amap, please do submit a feature request as an issue. If you end up working something out yourself, let me know, as others might be able to make use of it.

Lastly, I'm ccing @fedeclaudi just in case I've said anything wrong about brainrender.

**Comment by FedeClaudi** [comment]
Re: brainrender, it's all correct. Just notice that `brainrender.scene.add_image()` will be replaced in the future though methods to extract meshes from 3d images will still be part of brainrender. 

If you want to look at 3d images you can also use vtkplotter/vedo's [`Slicer()`](https://github.com/marcomusy/vedo/releases/tag/2020.3.0)

**Comment by rdbcasillas** [comment]
Thanks for that useful info!  Can the output directory of amap become input for cellfinder? Like: 

```
cellfinder -s <folder with 2d tiff files> -b <registration output of amap> -o <output path> 
```

If not, how do I make sure that cellfinder takes the background's registration results when counting cells?
