### ISSUE TITLE
[BUG] amap.conf.custom is not created automatically

### ISSUE THREAD

**Issue by ablot** [SainsburyWellcomeCentre/cellfinder#129]
If I install cellfinder but download the atlas in a custom path, running `cellfinder --summarise` fails with `KeyError: 'atlas'`. 

`get_structures_path` is looking for a amap.conf.custom and doesn't find it and crash. Creating this file by simply making a copy of `cellfinder.config.custom` in the amap folder solves the issue.

I guess the proper behaviour would be to have `cellfinder_download` with `--install-path` specified creating a cellfinder.config.custom **and** amap.config.custom.

**Comment by adamltyson** [comment]
Good catch. This shouldn't have happened anyway, as `get_structures_path` should have been looking for the cellfinder config file.

I'm going to leave this issue open, but the issue should be resolved once cellfinder relies on [brainreg](https://github.com/brainglobe/brainreg) and not amap.

**Comment by adamltyson** [comment]
Fixed in 0.4.0 ([brainreg branch](https://github.com/SainsburyWellcomeCentre/cellfinder/tree/brainreg)).
