### ISSUE TITLE
[BUG] cellfinder_curate fails with "from PySide2.QtWidgets import QApplication ImportError: DLL load failed: The specified procedure could not be found."

### ISSUE THREAD

**Issue by rdbcasillas** [SainsburyWellcomeCentre/cellfinder#131]
**Describe the bug**
When running cellfinder_curate for training, I get the following error: 

```
Traceback (most recent call last):
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\brainrender\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\brainrender\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\7057mehrav\AppData\Local\Continuum\anaconda3\envs\brainrender\Scripts\cellfinder_curate.exe\__main__.py", line 4, in <module>
  File "c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\brainrender\lib\site-packages\cellfinder\train\curation.py", line 7, in <module>
    from PySide2.QtWidgets import QApplication
ImportError: DLL load failed: The specified procedure could not be found.
```

**To Reproduce**
Following is the command I ran which produced this error:

```
cellfinder_curate "C:\Users\7057mehrav\Documents\new-file-structure\146\146-cells-rotated" "C:\Users\7057mehrav\Documents\new-file-structure\146\146-background-rotated" "C:\Users\7057mehrav\Documents\new-file-structure\146\output-rotated-rerun\cell_classification.xml" -o "C:\Users\7057mehrav\Documents\new-file-structure\146\output-rotated-rerun\training" -x 10 -y 10 -z 10
```

**Expected behavior**
Training data is generated

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I looked into this error and found [this stackoverflow thread](https://stackoverflow.com/questions/56757044/pyside2-dll-load-failed-the-specified-procedure-could-not-be-found) related to it. I have tried the accepted solution but it didn't change anything for me. Do I need to have specific versions of PySide2 and shiboken2?

**Comment by rdbcasillas** [comment]
Fixed it. So basically PySide2, shiboken2 and PyQt5 all three have to be the exact same version (in this case 5.15.0) so pip upgrade of PyQt5 fixed the issue

**Comment by adamltyson** [comment]
Sorry for the delay, and glad you found a solution.

I wonder if this is an issue with the various versions required by cellfinder, or whether it's an issue with other software you have installed in the environment. Does this same issue appear in a fresh conda environment when only cellfinder has been installed?

I ask because you shouldn't need PySide2 at all for cellfinder.
