### ISSUE TITLE
Does it work on individual brain slices?

### ISSUE THREAD

**Issue by jel0624** [SainsburyWellcomeCentre/cellfinder#52]

**Comment by adamltyson** [comment]
Currently it's only set up for registration of whole brains. However, I think at at least one lab has used the cell detection part on its own on single sections.

2D is on my to-do list, particularly getting 2D sections registered to the 3D template for visualisation. If you have some data you could share, drop me an email and I'll what can be done.

**Comment by adamltyson** [comment]
There seems to be a lot of demand for 2D support, so this might be done in the near future. Closing the issue, but please get in touch if you have data you can share, or you want to get involved.
