### ISSUE TITLE
[BUG] More than 1024 cells in the cell viewer can cause crashes.

### ISSUE THREAD

**Issue by adamltyson** [SainsburyWellcomeCentre/cellfinder#57]
This is a napari bug, fixed, but not yet released (https://github.com/napari/napari/issues/932).

If a new napari release is a way off, maybe install napari from github? (or just add to troubleshooting).

**Comment by adamltyson** [comment]
From twitter:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">We can round up a couple of very close PRs / minor bug fixes and then start the release process today / tomorrow targeting a release early this week. I had been thinking it might be nice to wait for the io-plugin PR 937 to go in, but fine for that to wait for 0.2.13.</p>&mdash; Nicholas Sofroniew (@sofroniewn) <a href="https://twitter.com/sofroniewn/status/1231686591288086529?ref_src=twsrc%5Etfw">February 23, 2020</a></blockquote> 

Looks like we can fix this by waiting, and then pinning `napari>=0.2.12` when it's released.

**Comment by sofroniewn** [comment]
@adamltyson we have now generated a new release candidate `0.2.12rc0` which can be tested with `pip install --pre napari` or `pip install -U --pre napari` for an upgrade. If you can give it a test and let us know if it works for you that would be great. We're doing some testing right now and I imagine I will make the release tonight

**Comment by adamltyson** [comment]
@sofroniewn all my napari-based viewers work as expected, and https://github.com/napari/napari/issues/932 is fixed.
Thanks!

**Comment by sofroniewn** [comment]
Great, thanks!

**Comment by sofroniewn** [comment]
`0.2.12` is out - sorry it took a little longer. I'll tweet about it tomorrow, but release notes are here https://github.com/napari/napari/releases/tag/v0.2.12

**Comment by adamltyson** [comment]
Great, thanks @sofroniewn!

**Comment by adamltyson** [comment]
Fixed in e90fd69173bff5889bbb2811a0b46bb63fef4fb1
