### ISSUE TITLE
[Feature] Save training weights regularly to interrupt without data loss

### ISSUE THREAD

**Issue by larsrollik** [SainsburyWellcomeCentre/cellfinder#59]
**Is your feature request related to a problem? Please describe.**
No. Just convenience.

**Describe the solution you'd like**
Save intermediate network weights after each epoch cycle in training, so that training can be manually stopped once loss plateaus.

**Describe alternatives you've considered**
None.

**Additional context**
.

**Comment by larsrollik** [comment]
Loss seems to converge already at ~30 epochs (out of 100) with 11 runs per epoch & 350sec per epoch to process. Parameters default except batch size = 128.

**Comment by adamltyson** [comment]
Linked to #61, this option exists (`--save-checkpoints`) but is not documented.

An option should be added to save every N epochs.

**Comment by adamltyson** [comment]
Documented in 8fbb2c09d1bd03e070b89be62652b71af1be6f33. Closing and moving "An option should be added to save every N epochs." to a new issue.
