### ISSUE TITLE
[Docs] Cell candidate detection parameters for non-standard voxel size

### ISSUE THREAD

**Issue by amedyukhina** [SainsburyWellcomeCentre/cellfinder#78]
This is rather a question on how to set up cell candidate detection if my data has a voxel size very different from the default values. 

The default voxel size, as I understand, is 2 um in xy and 5 um in z. My data has 0.875 in xy and 25 um in z. As a result, a lot of big cells are not detected at the stage of cell candidate detection. I have tried to play around with the size of the ball filter, but it has not changed a lot.

@adamltyson do you have any advice on how to choose the size of the ball filter depending on the size of the cells that I want to detect? (I have not yet figured out what exactly it does). Are there other parameters that could influence cell detection? Or would simply downsampling the images be the best solution?

Thanks in advance for any help with this.

**Comment by adamltyson** [comment]
This is a documentation issue, as I should make it clear that cellfinder is really designed for 3D cell detection, i.e. where your cell will appear in multiple z planes. I'm guessing this doesn't apply for your data. With 25um z spacing, this is essentially a 2D cell detection problem, that is not yet implemented in cellfinder.

I'm afraid off the top of my head I don't know how (or if) this can be solved easily (i.e. without adding full 2D cell detection support). There are a number of other parameters that can affect detection, and are listed in the `Cell candidate detection` section [here](https://sainsburywellcomecentre.github.io/cellfinder/main/user_guide/run.html#the-following-options-can-also-be-used). If you can share your data (even a subset of the planes), I can see what may work.

P.S. for general usage info like this, [gitter](https://gitter.im/cellfinder/celldetection?source=orgpage) might be a bit easier.

**Comment by amedyukhina** [comment]
I see, so this is probably not the issue of smaller xy size but rather the larger z-spacing. 

I will talk to my collaborators and see whether we can share the data. And thanks for your help!

**Comment by adamltyson** [comment]
Great, let me know. I'm closing this now, but I've opened a new issue (#79) for this issue generally.
