### ISSUE TITLE
[BUG] memory usage gets very high during cube extraction

### ISSUE THREAD

**Issue by stephenlenzi** [SainsburyWellcomeCentre/cellfinder#83]
**Describe the bug**
When running cellfinder_curate when running cube extraction memory usage gradually increases until I have to terminate it (at 48Gb).

**To Reproduce**
ran cellfinder_curate with two channels reclassified ~100 cells manually, saved and then ran extraction

**Expected behavior**
expected less memory to be used

**Log file**
Please attach the cellfinder log file (e.g. `output/cellfinder_2019-12-17_13-29-46.log`)
no log file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, Windows, MacOS]
 - Version [e.g. 18.04]
- Hardware specs [e.g. 128GB RAM, Xeon 4114 CPU]
Linux 4.15.0-76-generic x86_64
48Gb ram

**Additional context**

**Comment by adamltyson** [comment]
Is this still an issue?

**Comment by stephenlenzi** [comment]
no this is no longer an issue
